
package edu.vistas;

import edu.dao.DaoCoordinador;
import edu.dao.DaoEscuela;
import edu.modelo.Combo;
import edu.modelo.CoordinadorSSE;
import edu.modelo.Escuela;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import edu.utilidades.Validaciones;

/**
 * Nombre de la clase: FrmCoordinador
 * Version: 2.0
 * Fecha:11/08/18
 * CopyRight:SSE-ITCA
 * @author Roxana Menjivar
 */
public class FrmCoordinador extends javax.swing.JInternalFrame {

   DaoCoordinador daoC= new DaoCoordinador();
   CoordinadorSSE cor = new CoordinadorSSE();
   DaoEscuela daoE = new DaoEscuela();
   Validaciones validar = new Validaciones();
   Menu menu = new Menu();
   List<Combo> lista;
   Combo cmb = new Combo();
   
    public FrmCoordinador(){
        initComponents();
        mostrar();
        cargarCombo();
       // comboEscuela(jCmbEscuela, daoE.mostrarCarrera());
    }
    /*    
    public void comboEscuela(JComboBox cmb, List<Escuela> list) 
    {
        for (Escuela item : list) 
        {
            cmb.addItem(new ComboItem(item.getIdEscuela(), item.getNombre()));
        }
    }
    */
 
    public void cargarCombo()
    {
        lista = daoE.mostrarCarrera();
        for(int i=0;i<lista.size();i++)
        {
            cmb = new Combo(lista.get(i).getIdCombo(),lista.get(i).getDescripcion());
            this.jCmbEscuela.addItem(cmb.toString());    
        }    
    }
    
    public void mostrar()
    {
        String[] columnas={"Codigo","Nombre","Correo","Escuela"};
        Object[] obj =new Object[4];
        DefaultTableModel tabla = new DefaultTableModel(null,columnas);
        
        try 
        {
            List lista =daoC.mostrarCoordinador();
            for (int i = 0; i < lista.size(); i++) 
            {
                cor=(CoordinadorSSE)lista.get(i);
                obj[0]=cor.getIdCoordinador();
                obj[1]=cor.getNombre();
                obj[2]=cor.getCorreo();
                obj[3]=daoE.getidEscuela(cor.getIdEscuela()).getNombre();
                tabla.addRow(obj);
            }
            this.jTablaDatos.setModel(tabla);
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos en tabla ", "Carga Fallida "
                    + e.getMessage(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTxtCorreo = new javax.swing.JTextField();
        jBtnAgregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaDatos = new javax.swing.JTable();
        jBtnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBtnEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnEliminar = new javax.swing.JButton();
        jCmbEscuela = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jTxtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jCmbCarrera = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Control de Servicio Social Estudiantil");

        jBtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/ag.png"))); // NOI18N
        jBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarMouseClicked(evt);
            }
        });
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre:");

        jTablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaDatos);

        jBtnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/clear.png"))); // NOI18N
        jBtnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLimpiarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Codigo Usuario:");

        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/mod.png"))); // NOI18N
        jBtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEditarMouseClicked(evt);
            }
        });
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Codigo:");

        jBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/delete.png"))); // NOI18N
        jBtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEliminarMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Correo:");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Coordinador");

        jTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombreKeyTyped(evt);
            }
        });

        jTxtUsuario.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Escuela:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/users.png"))); // NOI18N

        jTxtCodigo.setEditable(false);

        jCmbCarrera.setEditable(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Carrera asignada:");

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(67, 67, 67)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(59, 59, 59)
                                .addComponent(jCmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(107, 107, 107)
                                .addComponent(jCmbEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(111, 111, 111)
                                .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jCmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
         
        String nombre = jTxtNombre.getText();
        String correo = jTxtCorreo.getText();

        int idEsc=0;
        
            for(int i=0;i<lista.size();i++)
            {
                if(jCmbEscuela.getSelectedItem().equals(lista.get(i).getDescripcion()))
                {
                     idEsc = lista.get(i).getIdCombo();
                }
            }
            
        CoordinadorSSE co = new CoordinadorSSE();
        co.setNombre(nombre);
        co.setCorreo(correo);
        co.setIdEscuela(idEsc);
        insertar(co);
        mostrar();
        limpiar();
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarMouseClicked

    }//GEN-LAST:event_jBtnAgregarMouseClicked

    private void jTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombreKeyTyped
        validar.wordsOnly(evt);
    }//GEN-LAST:event_jTxtNombreKeyTyped

    private void jTablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaDatosMouseClicked
       llenarTabla();
    }//GEN-LAST:event_jTablaDatosMouseClicked

    private void jBtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditarMouseClicked

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        try 
        {
            int idCoordinador = Integer.parseInt(jTxtCodigo.getText());
            String nombre = jTxtNombre.getText();
            String correo = jTxtCorreo.getText();

            int idEsc=0;
            for(int i=0;i<lista.size();i++)
            {
                if(jCmbEscuela.getSelectedItem().equals(lista.get(i).getDescripcion()))
                {
                     idEsc = lista.get(i).getIdCombo();
                }
            }

            CoordinadorSSE cor= new CoordinadorSSE();
            cor.setNombre(nombre);
            cor.setCorreo(correo);
            cor.setIdEscuela(idEsc);
            cor.setIdCoordinador(idCoordinador);

            if (!validar.IsNullOrEmpty(cor.getNombre())
                    && !validar.IsNullOrEmpty(cor.getCorreo())
                    && !validar.IsNullOrEmpty(String.valueOf(cor.getIdCoordinador()))) 
            {
                try 
                {
                    modificarCoordinador(cor);
                    limpiar();
                    mostrar();
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null,"Ocurrio un error al modificar " + ex.getMessage(),
                            "Modificacion Fallido",
                            JOptionPane.ERROR_MESSAGE);
                    limpiar();
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(null,"¡No dejar campos vacios! ",
                        "Datos Incompletos",
                        JOptionPane.WARNING_MESSAGE);
            }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Ocurrio un error al modificarrrrrrrr ",
                    "Modificacion Fallido",
                    JOptionPane.ERROR_MESSAGE);
            limpiar();
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLimpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_jBtnLimpiarMouseClicked

    private void jBtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarMouseClicked
        try 
        {
            int idCoordinador = Integer.parseInt(jTxtCodigo.getText());

            int SioNo = JOptionPane.showConfirmDialog(this, "¿Desea Eliminar el registro seleccionado?", 
                    "Eliminar Coordinador", JOptionPane.YES_NO_OPTION);

            if (SioNo == 0) 
            {
                daoC.eliminarCoordinador(idCoordinador);
                JOptionPane.showMessageDialog(null, "Se elimino exitosamente");
                mostrar();
                limpiar();
            }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Ocurrio un problema al eliminar el registro",
                    "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnEliminarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       this.setVisible(false);
        menu.cerrar();
        
    }//GEN-LAST:event_jButton1MouseClicked
    
    public void llenarTabla()
    {
        int index = this.jTablaDatos.getSelectedRow();

        if (index > -1) 
        {
         
            this.jTxtCodigo.setText(String.valueOf(this.jTablaDatos.getValueAt(index, 0)));
            this.jTxtNombre.setText(String.valueOf(this.jTablaDatos.getValueAt(index, 1)));
            this.jTxtCorreo.setText(String.valueOf(this.jTablaDatos.getValueAt(index, 2)));
            String escuela = String.valueOf(this.jTablaDatos.getValueAt(index, 3));
            jCmbEscuela.getModel().setSelectedItem(escuela);
     

        }
     }
    private void insertar(CoordinadorSSE cor)
    {
        try 
        {      
            daoC.insertarCoordinador(cor);
            JOptionPane.showMessageDialog(null, "Coordinador Guardado Exitosamente", "Actualizacion Correcta",
                    JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Ocurrio un error guardando " + e.getMessage(),
                    "Guardado Fallido",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void modificarCoordinador(CoordinadorSSE cor) 
    {
        int SioNo = JOptionPane.showConfirmDialog(this, "¿Desea modificar el registro seleccionado? ", "Modificar Empleado", 
                JOptionPane.YES_NO_OPTION);

        if (SioNo == 0) 
        {
            daoC.modificarCoordinador(cor);
            JOptionPane.showMessageDialog(null, "Coordinador Modificado Exitosamente", "Actualizacion Correcta", 
                    JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            mostrar();
        }
    }

    private void limpiar() 
    {
        jTxtCodigo.setText("");
        jTxtNombre.setText("");
        jTxtCorreo.setText("");
        jCmbEscuela.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCmbCarrera;
    private javax.swing.JComboBox<String> jCmbEscuela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaDatos;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
